name: Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Use Semgrep to analyze code
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@fcd5ab7459e8d91cb1777481980d1b18b4fc6735
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: ${{ secrets.SEMGREP_DEPLOYMENT_ID }}
          generateSarif: "1"

      # Use CodeQL to analyze code
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2

      - name: Build CodeQL database
        run: |
          codeql database create codeql-db --language=all
          codeql database analyze codeql-db --sarif=codeql.sarif

      # Upload Semgrep and CodeQL results using SARIF
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeql.sarif
        if: always()
